# Generated by Django 5.2 on 2025-05-15 15:13

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato')], max_length=20)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'db_table': '"animal"',
            },
        ),
        migrations.CreateModel(
            name='AnimalFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=app.models.caminho_foto)),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='app.animal')),
            ],
            options={
                'verbose_name': 'AnimalFoto',
                'verbose_name_plural': 'AnimaisFotos',
                'db_table': '"animal_foto"',
            },
        ),
        migrations.CreateModel(
            name='ResultadoTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_teste', models.CharField(max_length=100)),
                ('resultado', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testes', to='app.animal')),
            ],
            options={
                'verbose_name': 'ResultadoTeste',
                'verbose_name_plural': 'ResultadoTestes',
                'db_table': '"resultado_teste"',
            },
        ),
    ]
