# Generated by Django 5.2 on 2025-05-15 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='idade',
        ),
        migrations.AddField(
            model_name='animal',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
    ]
