# Generated by Django 5.2 on 2025-06-06 00:12

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_animalfoto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalfoto',
            name='imagem',
            field=models.ImageField(upload_to=app.models.caminho_foto),
        ),
    ]
