# Generated by Django 5.2 on 2025-05-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_animal_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalfoto',
            name='legenda',
        ),
        migrations.AlterField(
            model_name='animal',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
