# Generated by Django 5.2 on 2025-05-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_animalfoto_legenda_alter_animal_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoteste',
            name='resultado',
            field=models.CharField(max_length=200),
        ),
    ]
