# Generated by Django 5.2 on 2025-05-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_resultadoteste_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], default='cachorro', max_length=100),
        ),
    ]
