# Generated by Django 5.2 on 2025-05-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_animal_porte_alter_animal_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='porte',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=20),
        ),
    ]
