# Generated by Django 5.2 on 2025-05-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_animal_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
